### ISSUE TITLE
Minimizes on window switching

### ISSUE THREAD

**Issue by pramodsetlur** [erichlotto/Play-Music-Lyrics-Fetcher#8]
After switching windows or tabs, the open lyrics would have minimized. It takes another to click to open it again. 
I feel some good experience when I leave it open and switch tabs, so when i come back, i can still the lytics.

**Comment by erichlotto** [comment]
Actually that's a Chrome limitation: https://developer.chrome.com/extensions/faq#faq-persist-popups
The fix for this would be the usage of a panel component (like hangouts does) but right now I lack the time to develop this. If by any chance you're familiar with chrome extension development, feel free to work on it and send me a pull request.

**Comment by erichlotto** [comment]
In V1, the popup acts just like this, even with timing support
